name: Run the E2E test on kind
on:
  push: null
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the code
      uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
    - name: Fetch built CLI
      id: cli-cache
      uses: actions/cache@v4
      with:
        path: ./_output/bin/linux/amd64/velero
        key: velero-cli-${{ github.event.pull_request.number }}-${{ github.sha }}
    - name: Fetch built image
      id: image-cache
      uses: actions/cache@v4
      with:
        path: ./velero.tar
        key: velero-image-${{ github.event.pull_request.number }}-${{ github.sha }}
    - name: Build Velero CLI
      if: steps.cli-cache.outputs.cache-hit != 'true'
      run: 'make local

        '
    - name: Build Velero Image
      if: steps.image-cache.outputs.cache-hit != 'true'
      run: 'IMAGE=velero VERSION=pr-test BUILD_OUTPUT_TYPE=docker make container

        docker save velero:pr-test-linux-amd64 -o ./velero.tar

        '
  setup-test-matrix:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - name: Set k8s versions
      id: set-matrix
      run: "echo \"matrix={\\\n  \\\"k8s\\\":$(wget -q -O - \"https://hub.docker.com/v2/namespaces/kindest/repositories/node/tags?page_size=50\"\
        \ | grep -o '\"name\": *\"[^\"]*' | grep -o '[^\"]*$' | grep -v -E \"alpha|beta|1\\.3[2-9]\\.[1-9]|1\\\
        .31\\.[6-9]|1\\.30\\.[1-9][0-9]|1\\.29\\.[1-9][4-9]\" | grep -E \"v[1-9]\\.(2[5-9]|[3-9][0-9])\"\
        \ | awk -F. '{if(!a[$1\".\"$2]++)print $1\".\"$2\".\"$NF}' | sort -r | sed s/v//g | jq -R -c -s\
        \ 'split(\"\\n\")[:-1]'),\\\n  \\\"labels\\\":[\\\n    \\\"Basic && (ClusterResource || NodePort\
        \ || StorageClass)\\\", \\\n    \\\"ResourceFiltering && !Restic\\\", \\\n    \\\"ResourceModifier\
        \ || (Backups && BackupsSync) || PrivilegesMgmt || OrderedResources\\\", \\\n    \\\"(NamespaceMapping\
        \ && Single && Restic) || (NamespaceMapping && Multiple && Restic)\\\"\\\n  ]}\" >> $GITHUB_OUTPUT\n"
  run-e2e-test:
    needs:
    - build
    - setup-test-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.setup-test-matrix.outputs.matrix)}}
      fail-fast: false
    steps:
    - name: Check out the code
      uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
    - name: Install MinIO
      run: docker run -d --rm -p 9000:9000 -e "MINIO_ACCESS_KEY=minio" -e "MINIO_SECRET_KEY=minio123"
        -e "MINIO_DEFAULT_BUCKETS=bucket,additional-bucket" bitnami/minio:2021.6.17-debian-10-r7
    - uses: engineerd/setup-kind@v0.5.0
      with:
        version: v0.21.0
        image: kindest/node:v${{ matrix.k8s }}
    - name: Fetch built CLI
      id: cli-cache
      uses: actions/cache@v4
      with:
        path: ./_output/bin/linux/amd64/velero
        key: velero-cli-${{ github.event.pull_request.number }}-${{ github.sha }}
    - name: Fetch built Image
      id: image-cache
      uses: actions/cache@v4
      with:
        path: ./velero.tar
        key: velero-image-${{ github.event.pull_request.number }}-${{ github.sha }}
    - name: Load Velero Image
      run: kind load image-archive velero.tar
    - name: Run E2E test
      run: "cat << EOF > /tmp/credential\n[default]\naws_access_key_id=minio\naws_secret_access_key=minio123\n\
        EOF\n\n# Match kubectl version to k8s server version\ncurl -LO https://dl.k8s.io/release/v${{\
        \ matrix.k8s }}/bin/linux/amd64/kubectl\nsudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl\n\
        \nGOPATH=~/go \\\n    CLOUD_PROVIDER=kind \\\n    OBJECT_STORE_PROVIDER=aws \\\n    BSL_CONFIG=region=minio,s3ForcePathStyle=\"\
        true\",s3Url=http://$(hostname -i):9000 \\\n    CREDS_FILE=/tmp/credential \\\n    BSL_BUCKET=bucket\
        \ \\\n    ADDITIONAL_OBJECT_STORE_PROVIDER=aws \\\n    ADDITIONAL_BSL_CONFIG=region=minio,s3ForcePathStyle=\"\
        true\",s3Url=http://$(hostname -i):9000 \\\n    ADDITIONAL_CREDS_FILE=/tmp/credential \\\n   \
        \ ADDITIONAL_BSL_BUCKET=additional-bucket \\\n    VELERO_IMAGE=velero:pr-test-linux-amd64 \\\n\
        \    GINKGO_LABELS=\"${{ matrix.labels }}\" \\\n    make -C test/ run-e2e\n"
      timeout-minutes: 30
    - name: Upload debug bundle
      if: ${{ failure() }}
      uses: actions/upload-artifact@v4
      with:
        name: DebugBundle
        path: /home/runner/work/velero/velero/test/e2e/debug-bundle*
